export const coyolxauhqui = {
  title: "REARTICULATED COYOLXAUHQUI",
  altMonolito: "Coyolxauhqui Monolith",
  p1: `In Mexica (Aztec) cosmogony and theogony, <span class="font-bold">Coyolxauhqui</span> represents the moon and, likewise, the earth, agriculture and maize—that is, life—and, of course, also its cyclic complement, death. In a deeper sense, she represents the natural life/death cycle and, for warriors, life as an apprenticeship to learn how to die.`,
  p2: `<span class="font-bold">Coyolxauhqui</span> was the daughter of <span class="font-bold">Coatlicue</span>, the Great Cosmic Mother, and the leading sister of the multiple (“four hundred”) stars of the sky, the southern stars, and likewise, a symbol of multiple peoples. On one occasion, her mother became pregnant by an unknown person (legend says a ball of feathers fell from the sky and she sheltered it in her womb, becoming pregnant with <span class="font-bold">Huitzilopochtli</span>, god of the sun and also of war).`,
  p3: `Therefore, <span class="font-bold">Coyolxauhqui</span> and her sisters, the stars, decided to prevent said birth as it represented an affront to the customs of tribal endogamy. Thus they devised a plan to eliminate their unborn brother and <span class="font-bold">Coatlicue</span> for the affront, but <span class="font-bold">Huitzilopochtli</span>, learning of these intentions from the womb, told his mother to wait on the summit of a cosmic mount (the Coatepec) because he “already knew what he had to do.” And at the moment <span class="font-bold">Coyolxauhqui</span> and her sisters arrived at the foot of the mount, <span class="font-bold">Coatlicue</span> gave birth to <span class="font-bold">Huitzilopochtli</span>, the rising sun, who was born fully armed, representing the deity of the sun and also of war, the culture of subjugation and vassalage through violence.`,
  p4: `Attired as a warrior, <span class="font-bold">Coyolxauhqui</span> and the multiple stars (or peoples) climbed the mount and engaged in battle against the half-brother who, thanks to the tip-off from one of <span class="font-bold">Coyolxauhqui's</span> followers (betrayal), the support of his lieutenant (fraternity among men), and a powerful weapon (the power of armamentism), was able to face her, decapitate her, and hurl her head into the air, which became the moon. And not only that, but also to sever her body, dismembering arms and legs, symbolizing the division, fragmentation, and dispersion of the female lunar culture.`,
  p5: `Finally, he threw the fragmented body from the summit of the mount downwards, a clear disdain for lunar culture and an affirmation of the unique sovereignty of male solar culture at the peak of the mount, at the highest point of autocratic pyramidal power. Leaving <span class="font-bold">Coyolxauhqui's</span> body forever lying at the foot of the mount, understood as the pyramidal, vertical, and monolithic social structure, and as a warning of repression to women who might think of insubordinating to the power of men.`,
  p6: `This myth represents the daily process established between the moon, the power of female darkness, and the sun, the power of male light, which phallopatriarchy has interpreted as an antagonistic struggle and an act of violent subjugation rather than a natural cyclic process and complement.`,
  p7: `Here begins the break of the bond between mother and daughters as it is replaced by the bond between mother and son (Oedipus complex) and, furthermore, the forced identification of daughters with the father (Electra complex) no longer with the mother and, therefore, the beginning of competition with her and, as a consequence, the rivalry between women for the favor of men. A process that lesbian feminists do not fulfill, for which they are demonized, persecuted, and punished.`,
  p8: `Thus, from a lesbian-feminist perspective, the struggle, defeat, and disarticulation of <span class="font-bold">Coyolxauhqui</span> becomes a myth symbolizing the transition from matriarchy to patriarchy in Mesoamerica. The loss of community and gregarious power centered around women (collective property and the common good), through the impositive establishment of individualistic and ego-centered power focused on men (private property and personal good), remaining as millennial archetypes of the collective unconscious (Jung).`,
  p9: `And, consequently, the beginning of the era of colonialism, imperialism, classism, racism, sexism, and ecocide—that is, of human sacrifices (genocide, social exploitation) and the sacrifice of nature (depredation, ecological exploitation). <span class="font-bold underline">Rearticulating Coyolxauhqui and rescuing the community with her sisters (and brothers), that is, the peoples, is one of the fundamental purposes of ethno-eco-communist lesbian-feminism.</span>`,
  p10: `An additional and very current fact is that several authors mention that <span class="font-bold">Huitzilopochtli</span>, upon annihilating <span class="font-bold">Coyolxauhqui</span> and the multiple stars:`,
  p11: `“Stripped them of their attire (their culture); appropriated them (private property); put them on (self-adjudication); incorporated them into his destiny (historical theft) and made of them his own insignias and symbols (their own being and stolen representation)."`,
  p12: `Exactly what is currently happening in the postmodern queer neoliberal phallopatriarchy which is dedicated to re-subjugating women and re-enslaving them:`,
  p13: `Stripping them of their worldview and culture (feminism); appropriating their spaces (territorial, bodily, discursive, and legal); depriving them of their powers (mainly motherhood, giving life, and the capacity for community collective organization) and making them their own insignias or symbols (queer-transgenderist transvestism and transhumanism).`,
  interpretationsTitle: "INTERPRETATIONS OF COYOLXAUHQUI FROM THE FOLLOWING PERSPECTIVES:",
  perspectivas: [
    "Cosmogonic", "Theogonic", "Mythical", "Anthropological", "Historical",
    "Economic", "Political", "Psychological", "Symbolic", "Spiritual"
  ],
  inConstruction: "—— Section under construction ——"
};