export const decadas = {
  archiveName: "HISTORICAL ARCHIVE OF THE FEMINIST LESBIAN MOVEMENT IN MEXICO,",
  archiveSubtitle: "YAN MARÍA YAOYÓLOTL (AHMFLM-YMY)",
  title: `THE FEMINIST LESBIAN MOVEMENT<br/>
  THE REVOLUTIONARY DECADES OF THE 50s, 60s, AND 70s AND<br/>
  THE COUNTER-REVOLUTIONARY DECADES FROM THE 80s, 90s, AND 2000s TO DATE`,
  p1: "World history unfolds in periods that express the dynamics of international hegemonic economic systems and, therefore, the political, ecological, cultural, sexual, and symbolic systems built upon them (economy-sex-ethno-eco-politics). History does not progress linearly or mechanically, but irregularly, occasionally through great evolutionary or involutionary leaps. However, history is not a disconnected, directionless, or senseless development, as much of postmodern thought suggests.",
  p2: "History can be transformed and directed, as Marx or the utopians believed. The near future can and must be guided by the oppressed women of the world as a political course for the emancipation of all the oppressed on the planet. This is the only possibility to liberate humanity from imperialism and colonialism, classism and capitalism, racism and ethnocentrism, sexism and misogyny, and depredation and ecocide—toward the final abolition of phallopatriarchy, which is built on the backs of women.",
  p3: "After the end of World War II in 1945 and its continuation in the Cold War, three significant decades followed: the 50s, 60s, and 70s. These were characterized as deeply revolutionary due to the emergence of powerful anti-systemic social movements, ranging from independence struggles against colonialism and imperialism to emancipatory struggles against classism and racism, and liberation movements against sexism and ecological depredation worldwide.",
  p4: "The 50s were primarily distinguished by the independence struggles of colonized countries; the 60s by anti-racist, youth, and student movements; and the 70s by anti-sexist and environmentalist struggles. All three decades revolved around a global trend in Europe, Asia, Africa, and Latin America toward various types of socialism. In fact, by the late 70s, half the world was socialist or attempting to build its own version of socialism, communism, or even anarchism.",
  p5: "Faced with the danger these powerful anti-systemic movements posed to the interests of Big Capital, a new era of counter-revolutionary reactions began to halt, dismantle, and eliminate them during the 80s, 90s, and 2000s. this counter-revolution was driven by the economic model of Postmodern Neoliberal Globalization (PNG), aimed at propping up the failing capitalist system.",
  p6: "However, since the decadent, inhumane, and ecocidal patriarchal capitalist system could no longer offer anything good or new, it defended its continuity by recycling—resetting—itself through the appropriation and dispossession of many of the previous anti-systemic movements' proposals. It strengthened itself by co-opting these movements, confusing and disorienting them by inverting the oppressor/oppressed equation and creating the illusion of a world reaching true freedom through representative liberal democracy led by the U.S. empire.",
  p7: "The women's struggle movement—half of humanity—feminism, and as part of it, lesbian-feminism and lesbofeminism, is immersed in this reality and cannot be explained outside of it. This context explains why neo-patriarchal neo-capitalism launched a counter-revolutionary reaction specifically directed against this movement. This was done through gender ideology (gender theory or genderism) and queer ideology (queer theory or queerism), the official ideologies of the PNG system designed to re-establish and maintain the enslavement of women, while promoting a few empowered figures to create the appearance that women had reached power and were free, thus making feminism seemingly obsolete.",
  decade1970: {
    title: "THE 1970s",
    subtitle: "The rise of the feminist and lesbian-feminist movement in Mexico",
    description: "The 1960s and 1970s were marked by the intensification of global struggles against U.S. imperialism; the significant progress of the African-American anti-racist movement in the U.S. and the Black movement in South Africa; the emergence of radical youth and student movements against the capitalist system, many proposing armed struggle; the construction of the first Latin American socialist country in Chile and its annihilation by a CIA-led military coup; the U.S. failure and defeat in Vietnam; the Israeli war for the suppression of Palestine; the defense of local and regional autonomies; the counter-cultural rebellion against capitalist consumer society; and the environmental struggle against the depredation of large transnationals. It was within this historical context that the first lesbian-feminist organizations in Mexico began to develop.",
    button: "ENTER"
  }
};