export const coyolxauhqui = {
  title: "COYOLXAUHQUI REARTICULADA",
  altMonolito: "Monolito de Coyolxauhqui",
  p1: `En la cosmogonía y la teogonía mexica (azteca), <span class="font-bold">Coyolxauhqui</span> representa a la luna y, asimismo, a la tierra, a la agricultura y al maíz, es decir, a la vida, y, por supuesto, también a su complemento cíclico, la muerte. Ella representa en un sentido más profundo, el ciclo natural vida/muerte y para las guerreras, la vida como aprendizaje para aprender a morir.`,
  p2: `<span class="font-bold">Coyolxauhqui</span> fue hija de <span class="font-bold">Coatlicue</span>, la Gran Madre Cósmica, y hermana líder de las múltiples (“cuatrocientas”) estrellas del cielo, el estelar sur, y asimismo, símbolo de los múltiples pueblos. En una ocasión, su madre se embarazó de un desconocido (cuenta la leyenda que una bolita de plumas cayó del cielo y ella la resguardó en su vientre quedando embarazada, preñada de <span class="font-bold">Huitzilopochtli</span> dios del sol y, también, de la guerra).`,
  p3: `Por lo cual, <span class="font-bold">Coyolxauhqui</span> y sus hermanas, las estrellas, decidieron evitar dicho nacimiento ya que representaba una afrenta a las costumbres de la endogamia tribal. Así idearon un plan para eliminar a su hermano aún no nacido y a <span class="font-bold">Coatlicue</span> por la afrenta, pero al enterarse <span class="font-bold">Huitzilopochtli</span> de dichas intenciones, desde el vientre, le dijo a su madre que esperara en la cima de un monte cósmico (el Coatepec) porque él “ya sabía lo que tenía que hacer”. Y en el momento en que <span class="font-bold">Coyolxauhqui</span> y sus hermanas llegaron a las faldas del monte, <span class="font-bold">Coatlicue</span> parió a <span class="font-bold">Huitzilopochtli</span>, el sol naciente, quien nació completamente armado, representando a la deidad del sol y, también, de la guerra, la cultura del sometimiento y el vasallaje por la violencia.`,
  p4: `Ataviada como guerrera <span class="font-bold">Coyolxauhqui</span> y las múltiples estrellas (o pueblos) subieron al monte y entablaron una batalla contra el medio hermano quien gracias al sobreaviso de uno de los seguidores de <span class="font-bold">Coyolxauhqui</span> (traición); al apoyo de su lugarteniente (fraternidad entre hombres) y a una poderosa arma (el poder del armamentismo) pudo enfrentarla, decapitarla y lanzar su cabeza al aire, que se convirtió en la luna. Y no solo eso, sino, además, cercenar su cuerpo para desmembrar brazos y piernas simbolizando la división, fragmentación y dispersión de la cultura lunar femenina.`,
  p5: `Finalmente, aventó el cuerpo fragmentado de la cima del monte hacia abajo, un claro desdén de la cultura lunar y afirmación de la soberanía única de la cultura solar masculina en la cúspide del monte, en lo más alto del poder piramidal autócrata. Quedando el cuerpo de <span class="font-bold">Coyolxauhqui</span> para siempre tirado al pie del monte, entendido éste como la estructura social piramidal, vertical y monolítica, y como advertencia de represión a las mujeres que pensaran insubordinarse al poder de los hombres.`,
  p6: `Este mito representa el proceso diario que se establece entre la luna, el poder de la oscuridad femenino, y el sol, el poder de la luz masculino, que el falopatriarcado ha interpretado como una lucha antagónica y un acto de sometimiento violento y no un proceso y complemento natural cíclico.`,
  p7: `Aquí inicia el quiebre del vínculo entre madre e hijas al ser sustituido por el vínculo entre la madre y el hijo (complejo de Edipo) y, además, la identificación forzada de las hijas con el padre (complejo de Electra) ya no con la madre y, por tanto, el inicio de la competencia con esta y, como consecuencia, la rivalidad entre las mujeres por el favor de los hombres. Proceso que las lesbianas feministas no cumplen, por lo cual son satanizadas, perseguidas y castigadas.`,
  p8: `Así es como, desde una perspectiva lesbofeminista, la lucha, la derrota y la desarticulación de <span class="font-bold">Coyolxauhqui</span> se convierte en un mito que simboliza el paso del matriarcado al patriarcado en Mesoamérica. La pérdida del poder comunitario y gregario centrado en torno a las mujeres (la propiedad colectiva y el bien común), por la instauración impositiva del poder individualista y egocentrado enfocado en los hombres (la propiedad privada y el bien personal), quedando como arquetipos milenarios del inconsciente colectivo (Jung).`,
  p9: `Y, por consecuencia, el inicio de la era del colonialismo, el imperialismo, el clasismo, el racismo, el sexismo y el ecocidio, es decir, de los sacrificios humanos (genocidio, expoliación social) y del sacrificio de la naturaleza (depredación, expoliación ecológica). <span class="font-bold underline">Volver a rearticular a Coyolxauhqui y rescatar la comunidad con sus hermanas(os), es decir, los pueblos, es uno de los propósitos fundamentales del lesbofeminismo etno-eco-comunista.</span>`,
  p10: `Un dato adicional y muy actual, es que varios autores mencionan que <span class="font-bold">Huitzilopochtli</span> al aniquilar a <span class="font-bold">Coyolxauhqui</span> y a las múltiples estrellas:`,
  p11: `“Las despojó de sus atavíos (su cultura); se los apropió (propiedad privada); se los puso (auto adjudicación); los incorporó a su destino (robo histórico) e hizo de ellos sus propias insignias y símbolos (su propio ser y representación robados)".`,
  p12: `Exactamente lo que está sucediendo actualmente en el falopatriarcado neoliberal posmoderno queer que se encuentra abocado a resometer a las mujeres y a reesclavizarlas:`,
  p13: `Quitándoles su cosmovisión y cultura (el feminismo); apropiándose de sus espacios (territoriales, corporales, discursivos y jurídicos); despojándolas de sus poderes (principalmente la maternidad, dar vida, y la capacidad de organización colectiva comunitaria) y haciéndolos sus propias insignias o símbolos (el travestismo queer-transgenerista y el transhumanismo).`,
  interpretationsTitle: "INTERPRETACIONES DE COYOLXAUHQUI DESDE LAS SIGUIENTES PERSPECTIVAS:",
  perspectivas: [
    "La cosmogónica", "La teogónica", "La mítica", "La antropológica", "La histórica",
    "La económica", "La política", "La psicológica", "La simbólica", "La espiritual"
  ],
  inConstruction: "—— Sección en construcción ——"
};