export const decadas = {
  archiveName: "ARCHIVO HISTÓRICO DEL MOVIMIENTO FEMINISTA DE LESBIANAS EN MÉXICO,",
  archiveSubtitle: "YAN MARÍA YAOYÓLOTL (AHMFLM-YMY)",
  title: `EL MOVIMIENTO FEMINISTA DE LESBIANAS<br/>
  LAS REVOLUCIONARIAS DÉCADAS DE LOS 50, 60 Y 70 Y<br/>
  LAS CONTRARREVOLUCIONARIAS DÉCADAS DE LOS 80, 90 Y 2000 A LA FECHA`,
  p1: "La historia mundial se desarrolla por períodos que expresan la dinámica de los sistemas económicos hegemónicos a nivel internacional y, por lo tanto, de los sistemas políticos, ecológicos, culturales, sexuales y simbólicos que se edifican sobre ellos (economía-sexo-etno-eco-política). Pero no de manera lineal ni mecánica sino irregular y ocasionalmente a grandes saltos evolutivos o, también, involutivos; sin embargo, la historia no representa un desarrollo inconexo, sin direccionalidad, voluntarista o sin sentido como lo ve la mayor parte del pensamiento posmoderno.",
  p2: "La historia puede transformarse y direccionarse como pensaba Marx, o los utopistas. La historia próxima futura la pueden, y deben, orientar las mujeres oprimidas del mundo como dirección política para la emancipación de todos los oprimidos del planeta. Única posibilidad de liberar a la humanidad del imperialismo y colonialismo; el clasismo y capitalismo; el racismo y etnocentrismo; el sexismo y misoginia y la depredación y ecocidio, es decir, hacia la abolición definitiva del falopatriarcado porque éste se edifica sobre la espalda de las mujeres.",
  p3: "Al terminar la Segunda Guerra Mundial en 1945 y su continuación en la Guerra Fría, le siguieron tres importantes décadas, los 50, 60 y los 70 que se caracterizaron por ser profundamente revolucionarias debido al surgimiento de grandes y poderosos movimientos sociales antisistémicos, desde las luchas de independencia contra el colonialismo y el imperialismo y las luchas emancipatorias contra el clasismo y el racismo, hasta las luchas de liberación contra el sexismo y la depredación ecológica a nivel mundial.",
  p4: "Los 50 se distinguieron principalmente por las luchas de independencia de los países colonizados; los 60 principalmente por las luchas antirracistas, juveniles y estudiantiles y los 70 especialmente por las luchas antisexistas y ecologistas. Pero las tres décadas giraron en torno a la gran tendencia mundial de Europa, Asia, África y Latinoamérica hacia los diferentes tipos de socialismos. De hecho, para finales de los 70, la mitad del mundo era socialista o estaba intentando construir su propia versión de socialismo o de comunismo e inclusive, de anarquismo.",
  p5: "Ante el peligro que representaron dichos poderosos movimientos antisistémicos para los intereses del Gran Capital, este inició una nueva época de reacciones contrarrevolucionarias con el fin de frenarlos, desarticularlos y eliminarlos durante las décadas 80, 90 y los 2000 hasta la actualidad. Contrarrevolución impulsada por el modelo económico de la Globalización Neoliberal Posmoderna (GNP), cuyo objetivo era apuntalar al fracasado sistema capitalista.",
  p6: "Sin embargo, dado que el decadente, inhumano y ecocida sistema patriarcal capitalista ya no podía ofrecer nada bueno ni nuevo, defendió su continuidad reciclándose -reseteándose- a través de la apropiación y despojo de muchos de los planteamientos de los movimientos antisistémicos anteriores, con el fin de fortalecerse y de resometer a esos mismos movimientos travistiéndose de ellos mismos a fin de confundir y desorientar invirtiendo la ecuación opresores/oprimidos y creando la ilusión de la llegada del mundo a la verdadera libertad expresada en la democracia liberal representativa liderada por el imperio estadounidense.",
  p7: "El movimiento de lucha de las mujeres -la mitad de la humanidad- el feminismo, y como parte de éste el lesbianismo-feminista y el lesbofeminismo, se encuentra inmerso en esta realidad y fuera de ella no puede explicarse. Contexto que permite entender, por tanto, la razón por la cual el neopatriarcado neocapitalista impulsó una reacción contrarrevolucionaria dirigida específicamente contra éste movimiento, por un lado, a través de la ideología de género, teoría de género (TG) o generismo, y, por otro lado, a través de la ideología queer, teoría queer (TQ) o queerismo, como las ideologías oficiales del sistema de la globalización neoliberal posmoderna (GNP) diseñadas específicamente para reestablecer y mantener la esclavitud de las mujeres, paralela al encumbramiento de algunas personajas empoderadas para aparentar que las mujeres ya habían llegado al poder y ya eran libres y, por ende, el feminismo ya era inservible.",
  decade1970: {
    title: "DÉCADA 1970",
    subtitle: "El ascenso del movimiento feminista y lésbico-feminista en México",
    description: "Las décadas 1960 y 1970 del pasado siglo XX se encuentran marcadas por la intensificación de la lucha de los pueblos del mundo contra el imperialismo estadounidense; el gran avance del movimiento antirracista afroamericano en EE. UU. y negro en Sudáfrica; la emergencia de radicales movimientos juveniles y estudiantiles contra el sistema capitalista planteando, muchos de ellos, la lucha armada; la construcción del primer país socialista latinoamericano en Chile y su aniquilación por un golpe militar dirigido por la CIA; el fracaso y derrota estadounidense en Vietnam; la guerra israelí por la supresión de Palestina; la defensa de las autonomías locales y regionales, aún por la vía armada; la rebelión contracultural contra la sociedad de consumo capitalista y la lucha ecologista contra la depredación de las grandes transnacionales, entre otros. En este contexto histórico es que empezaron a desarrollarse las primeras organizaciones de lesbianas-feministas en México.",
    button: "ENTRAR"
  }
};